// Auto-generated by scripts/generate-audio.mjs — do not edit by hand.
export type AudioSentence = { start: number; duration: number; text: string };
export type AudioSegment = { speaker: string; start: number; duration: number; sentences: AudioSentence[] };
export type AudioEntry = { group: string; src: string; bitrate: number; durationSec: number; segments: AudioSegment[] };

export const audioManifest: Record<string, AudioEntry> = {
  "L1": {
    "group": "mock01",
    "src": "/audio/mock01/L1.mp3",
    "bitrate": 96,
    "durationSec": 56.88,
    "segments": [
      {
        "speaker": "AGENT",
        "start": 0,
        "duration": 5.21,
        "sentences": [
          {
            "start": 0.1,
            "duration": 3.125,
            "text": "Halton Home Services, this is Priya."
          },
          {
            "start": 3.175,
            "duration": 1.975,
            "text": "How may I help you?"
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 5.21,
        "duration": 5.09,
        "sentences": [
          {
            "start": 0.1,
            "duration": 4.988,
            "text": "Hi — I've got water coming through the ceiling of my kitchen from the bathroom upstairs."
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 10.3,
        "duration": 5.54,
        "sentences": [
          {
            "start": 0.1,
            "duration": 2.263,
            "text": "I'm sorry to hear that."
          },
          {
            "start": 2.313,
            "duration": 3.163,
            "text": "Have you turned off the water at the main valve?"
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 15.84,
        "duration": 3.02,
        "sentences": [
          {
            "start": 0.1,
            "duration": 2.913,
            "text": "Not yet — I wasn't sure where it is."
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 18.86,
        "duration": 7.08,
        "sentences": [
          {
            "start": 0.1,
            "duration": 3.313,
            "text": "It's usually in the basement near the front wall."
          },
          {
            "start": 3.363,
            "duration": 3.65,
            "text": "I'd turn it off right away to stop further damage."
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 25.94,
        "duration": 4.56,
        "sentences": [
          {
            "start": 0.1,
            "duration": 2.25,
            "text": "Okay, I'll do that now."
          },
          {
            "start": 2.3,
            "duration": 2.2,
            "text": "How soon can someone come?"
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 30.5,
        "duration": 6,
        "sentences": [
          {
            "start": 0.1,
            "duration": 3.4,
            "text": "We have a plumber finishing a job in your area."
          },
          {
            "start": 3.45,
            "duration": 2.488,
            "text": "He can be there within the hour."
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 36.5,
        "duration": 3.34,
        "sentences": [
          {
            "start": 0.1,
            "duration": 1.538,
            "text": "That's fine."
          },
          {
            "start": 1.588,
            "duration": 1.7,
            "text": "What's the cost?"
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 39.84,
        "duration": 14.33,
        "sentences": [
          {
            "start": 0.1,
            "duration": 5.125,
            "text": "There's a standard call-out fee of eighty dollars, covering the first thirty minutes."
          },
          {
            "start": 5.175,
            "duration": 4.375,
            "text": "After that it's billed per fifteen-minute block at twenty-five dollars."
          },
          {
            "start": 9.55,
            "duration": 4.713,
            "text": "Parts are extra, but we'll confirm any cost before starting repairs."
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 54.17,
        "duration": 2.71,
        "sentences": [
          {
            "start": 0.1,
            "duration": 2.613,
            "text": "Great — please send someone over."
          }
        ]
      }
    ]
  },
  "L2": {
    "group": "mock01",
    "src": "/audio/mock01/L2.mp3",
    "bitrate": 96,
    "durationSec": 40.73,
    "segments": [
      {
        "speaker": "LEE",
        "start": 0,
        "duration": 2.35,
        "sentences": [
          {
            "start": 0.05,
            "duration": 1.2,
            "text": "You look tired."
          },
          {
            "start": 1.25,
            "duration": 1.038,
            "text": "Long week?"
          }
        ]
      },
      {
        "speaker": "MARA",
        "start": 2.35,
        "duration": 4.99,
        "sentences": [
          {
            "start": 0.05,
            "duration": 1.263,
            "text": "Tell me about it."
          },
          {
            "start": 1.313,
            "duration": 3.625,
            "text": "I've been working late every night because of a project deadline."
          }
        ]
      },
      {
        "speaker": "LEE",
        "start": 7.34,
        "duration": 4.44,
        "sentences": [
          {
            "start": 0.05,
            "duration": 4.338,
            "text": "Well, the good news is the weather's supposed to be beautiful this weekend."
          }
        ]
      },
      {
        "speaker": "MARA",
        "start": 11.78,
        "duration": 4.32,
        "sentences": [
          {
            "start": 0.05,
            "duration": 0.75,
            "text": "Really?"
          },
          {
            "start": 0.8,
            "duration": 3.463,
            "text": "I was thinking of finally checking out that new trail by the river."
          }
        ]
      },
      {
        "speaker": "LEE",
        "start": 16.1,
        "duration": 6.1,
        "sentences": [
          {
            "start": 0.05,
            "duration": 5.988,
            "text": "I did it last Saturday — it's about six kilometres, mostly flat, and there's a little cafe at the halfway point."
          }
        ]
      },
      {
        "speaker": "MARA",
        "start": 22.2,
        "duration": 3.67,
        "sentences": [
          {
            "start": 0.05,
            "duration": 1.6,
            "text": "That sounds perfect."
          },
          {
            "start": 1.65,
            "duration": 1.963,
            "text": "Are you free on Sunday morning?"
          }
        ]
      },
      {
        "speaker": "LEE",
        "start": 25.87,
        "duration": 3.77,
        "sentences": [
          {
            "start": 0.05,
            "duration": 3.65,
            "text": "I have a dentist appointment at nine, but I could meet you around eleven."
          }
        ]
      },
      {
        "speaker": "MARA",
        "start": 29.64,
        "duration": 4.44,
        "sentences": [
          {
            "start": 0.05,
            "duration": 1.338,
            "text": "Eleven works."
          },
          {
            "start": 1.388,
            "duration": 3,
            "text": "Should we drive separately or meet at the trailhead?"
          }
        ]
      },
      {
        "speaker": "LEE",
        "start": 34.08,
        "duration": 4.01,
        "sentences": [
          {
            "start": 0.05,
            "duration": 3.888,
            "text": "The parking lot fills up early, so I'll pick you up at ten forty-five."
          }
        ]
      },
      {
        "speaker": "MARA",
        "start": 38.09,
        "duration": 2.64,
        "sentences": [
          {
            "start": 0.05,
            "duration": 2.525,
            "text": "Great — I'll bring water and a hat."
          }
        ]
      }
    ]
  },
  "L3": {
    "group": "mock01",
    "src": "/audio/mock01/L3.mp3",
    "bitrate": 96,
    "durationSec": 49.75,
    "segments": [
      {
        "speaker": "ANNOUNCER",
        "start": 0,
        "duration": 49.75,
        "sentences": [
          {
            "start": 0.1,
            "duration": 4.238,
            "text": "Welcome to the Riverside Public Library's fall program launch."
          },
          {
            "start": 4.288,
            "duration": 4.063,
            "text": "Starting October first, we're introducing three new services."
          },
          {
            "start": 8.35,
            "duration": 8.113,
            "text": "First, an extended Saturday storytime for children aged three to six, running from ten to eleven in the community room."
          },
          {
            "start": 16.463,
            "duration": 11.05,
            "text": "Second, a free digital-skills help desk every Tuesday and Thursday afternoon, where volunteers can assist with phones, tablets and laptops — no appointment needed."
          },
          {
            "start": 27.513,
            "duration": 11.35,
            "text": "Third, a home-delivery service for cardholders who cannot visit the library in person; deliveries go out every second Wednesday and can be arranged by phone or through our website."
          },
          {
            "start": 38.863,
            "duration": 5.913,
            "text": "All three services are free, but storytime and home delivery require registration in advance."
          },
          {
            "start": 44.775,
            "duration": 4.975,
            "text": "Registration opens this Friday at nine a.m. at the front desk and online."
          }
        ]
      }
    ]
  },
  "L4": {
    "group": "mock01",
    "src": "/audio/mock01/L4.mp3",
    "bitrate": 96,
    "durationSec": 45.79,
    "segments": [
      {
        "speaker": "NEWS READER",
        "start": 0,
        "duration": 45.79,
        "sentences": [
          {
            "start": 0.05,
            "duration": 6.65,
            "text": "The city council voted last night to approve funding for a new pedestrian bridge across the Don Valley."
          },
          {
            "start": 6.7,
            "duration": 9.05,
            "text": "The bridge, which will connect the Eastside neighbourhood with the downtown core, is expected to cost eighteen million dollars and take two years to complete."
          },
          {
            "start": 15.75,
            "duration": 6.25,
            "text": "Construction is scheduled to begin next spring, following a final public consultation in December."
          },
          {
            "start": 22,
            "duration": 6.975,
            "text": "Supporters say the bridge will cut the current forty-minute walking detour down to just ten minutes and encourage cycling."
          },
          {
            "start": 28.975,
            "duration": 7.475,
            "text": "Opponents argue the money would be better spent repairing existing roads, several of which have been closed since last winter's flooding."
          },
          {
            "start": 36.45,
            "duration": 9.288,
            "text": "The mayor called the decision 'a long-term investment in a greener, more connected city', while acknowledging that some road repairs will be delayed as a result."
          }
        ]
      }
    ]
  },
  "L5": {
    "group": "mock01",
    "src": "/audio/mock01/L5.mp3",
    "bitrate": 96,
    "durationSec": 69.4,
    "segments": [
      {
        "speaker": "HOST",
        "start": 0,
        "duration": 14.52,
        "sentences": [
          {
            "start": 0.1,
            "duration": 1.8,
            "text": "Welcome back."
          },
          {
            "start": 1.85,
            "duration": 4.875,
            "text": "Today we're asking: has the shift to remote work been good for our cities?"
          },
          {
            "start": 6.725,
            "duration": 5.125,
            "text": "With me are economist Dr. Elena Roth and small-business owner Marcus Webb."
          },
          {
            "start": 11.85,
            "duration": 2.6,
            "text": "Elena, let's start with you."
          }
        ]
      },
      {
        "speaker": "ELENA",
        "start": 14.52,
        "duration": 12.17,
        "sentences": [
          {
            "start": 0.05,
            "duration": 0.825,
            "text": "Thanks."
          },
          {
            "start": 0.875,
            "duration": 2,
            "text": "The data shows a clear split."
          },
          {
            "start": 2.875,
            "duration": 9.225,
            "text": "Knowledge workers report higher satisfaction and save commuting costs, but downtown businesses have lost foot traffic — lunch spots and transit have felt it most."
          }
        ]
      },
      {
        "speaker": "HOST",
        "start": 26.69,
        "duration": 3.38,
        "sentences": [
          {
            "start": 0.1,
            "duration": 3.275,
            "text": "Marcus, you run a print shop downtown."
          }
        ]
      },
      {
        "speaker": "MARCUS",
        "start": 30.07,
        "duration": 10.22,
        "sentences": [
          {
            "start": 0.05,
            "duration": 0.95,
            "text": "That's right."
          },
          {
            "start": 1,
            "duration": 3.213,
            "text": "Our daytime customers dropped by almost half."
          },
          {
            "start": 4.213,
            "duration": 5.95,
            "text": "But we've adapted — we now offer delivery and early-evening hours, and we've kept everyone employed."
          }
        ]
      },
      {
        "speaker": "HOST",
        "start": 40.29,
        "duration": 2.83,
        "sentences": [
          {
            "start": 0.1,
            "duration": 2.713,
            "text": "Elena, what about the long term?"
          }
        ]
      },
      {
        "speaker": "ELENA",
        "start": 43.12,
        "duration": 12.55,
        "sentences": [
          {
            "start": 0.05,
            "duration": 3.013,
            "text": "Offices aren't disappearing; they're changing."
          },
          {
            "start": 3.063,
            "duration": 3.188,
            "text": "We're likely to settle on three days in, two days out."
          },
          {
            "start": 6.25,
            "duration": 6.25,
            "text": "That hybrid model spreads demand more evenly and is better for the city's finances than full remote."
          }
        ]
      },
      {
        "speaker": "MARCUS",
        "start": 55.67,
        "duration": 9.34,
        "sentences": [
          {
            "start": 0.05,
            "duration": 1.388,
            "text": "I'd agree with that."
          },
          {
            "start": 1.438,
            "duration": 7.85,
            "text": "A steady three-day week would bring enough people back to keep the lunch economy alive, without losing the flexibility workers now expect."
          }
        ]
      },
      {
        "speaker": "HOST",
        "start": 65.01,
        "duration": 4.39,
        "sentences": [
          {
            "start": 0.1,
            "duration": 2.35,
            "text": "So a middle path, then."
          },
          {
            "start": 2.4,
            "duration": 1.938,
            "text": "Thanks to you both."
          }
        ]
      }
    ]
  },
  "L6": {
    "group": "mock01",
    "src": "/audio/mock01/L6.mp3",
    "bitrate": 96,
    "durationSec": 46.49,
    "segments": [
      {
        "speaker": "SPEAKER A",
        "start": 0,
        "duration": 23.33,
        "sentences": [
          {
            "start": 0.05,
            "duration": 2.463,
            "text": "E-bikes have no place on our park trails."
          },
          {
            "start": 2.513,
            "duration": 7.238,
            "text": "Trails are for walking and traditional cycling, and motor-assisted bikes move too fast for a space meant for families and dogs."
          },
          {
            "start": 9.75,
            "duration": 2.275,
            "text": "I've nearly been clipped twice this month."
          },
          {
            "start": 12.025,
            "duration": 4.3,
            "text": "If we allow e-bikes everywhere, we'll push walkers out of the parks entirely."
          },
          {
            "start": 16.325,
            "duration": 6.938,
            "text": "A speed limit is unenforceable on a narrow path, so the only fair rule is to keep motor power off the trails."
          }
        ]
      },
      {
        "speaker": "SPEAKER B",
        "start": 23.33,
        "duration": 23.16,
        "sentences": [
          {
            "start": 0.05,
            "duration": 8.075,
            "text": "I understand the worry, but a blanket ban ignores who actually rides e-bikes — commuters and older riders who otherwise wouldn't cycle at all."
          },
          {
            "start": 8.125,
            "duration": 3.45,
            "text": "The real issue isn't the motor; it's courtesy."
          },
          {
            "start": 11.575,
            "duration": 7.975,
            "text": "A fifteen-kilometre speed limit, clearly posted, plus fines for reckless riding, would let everyone share the trail safely."
          },
          {
            "start": 19.55,
            "duration": 3.55,
            "text": "We shouldn't punish a whole group for the behaviour of a few."
          }
        ]
      }
    ]
  },
  "lst-01": {
    "group": "practice",
    "src": "/audio/practice/lst-01.mp3",
    "bitrate": 96,
    "durationSec": 44.52,
    "segments": [
      {
        "speaker": "AGENT",
        "start": 0,
        "duration": 4.92,
        "sentences": [
          {
            "start": 0.1,
            "duration": 2.85,
            "text": "TechFix support, Maya speaking."
          },
          {
            "start": 2.9,
            "duration": 1.963,
            "text": "How can I help you?"
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 4.92,
        "duration": 7.8,
        "sentences": [
          {
            "start": 0.1,
            "duration": 5.4,
            "text": "Hi — I bought a laptop charger from your website last week and it arrived already cracked."
          },
          {
            "start": 5.45,
            "duration": 2.3,
            "text": "The cable's frayed near the tip."
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 12.72,
        "duration": 5.5,
        "sentences": [
          {
            "start": 0.1,
            "duration": 2.188,
            "text": "I'm sorry about that."
          },
          {
            "start": 2.238,
            "duration": 3.188,
            "text": "Could you share your order number so I can look it up?"
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 18.22,
        "duration": 3.62,
        "sentences": [
          {
            "start": 0.1,
            "duration": 3.525,
            "text": "Sure, it's 8-3-2-1-7-0-4."
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 21.84,
        "duration": 10.39,
        "sentences": [
          {
            "start": 0.1,
            "duration": 1.525,
            "text": "Thanks."
          },
          {
            "start": 1.575,
            "duration": 3.5,
            "text": "I can see the order was placed six days ago."
          },
          {
            "start": 5.075,
            "duration": 5.263,
            "text": "We'll send a replacement free of charge, and you don't need to return the damaged one."
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 32.23,
        "duration": 3.65,
        "sentences": [
          {
            "start": 0.1,
            "duration": 1.525,
            "text": "That's great."
          },
          {
            "start": 1.575,
            "duration": 2.025,
            "text": "How long will it take?"
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 35.88,
        "duration": 6.31,
        "sentences": [
          {
            "start": 0.1,
            "duration": 3.025,
            "text": "Around three to five business days."
          },
          {
            "start": 3.075,
            "duration": 3.175,
            "text": "You'll receive a tracking email shortly."
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 42.19,
        "duration": 2.33,
        "sentences": [
          {
            "start": 0.1,
            "duration": 2.225,
            "text": "Perfect, that solves it."
          }
        ]
      }
    ]
  },
  "lst-02": {
    "group": "practice",
    "src": "/audio/practice/lst-02.mp3",
    "bitrate": 96,
    "durationSec": 30.46,
    "segments": [
      {
        "speaker": "ANNOUNCER",
        "start": 0,
        "duration": 30.46,
        "sentences": [
          {
            "start": 0.1,
            "duration": 4.075,
            "text": "Avo Cafe on Maple Street has just launched its autumn menu."
          },
          {
            "start": 4.125,
            "duration": 8.988,
            "text": "From today until the end of November, every weekday between three and five, you can grab a seasonal drink and any sandwich for nine dollars."
          },
          {
            "start": 13.113,
            "duration": 6.55,
            "text": "The new menu features a pumpkin latte, pear and gorgonzola toastie, and a maple butter brioche."
          },
          {
            "start": 19.663,
            "duration": 5.4,
            "text": "Students who show a valid ID also receive a ten percent discount on bakery items."
          },
          {
            "start": 25.063,
            "duration": 5.388,
            "text": "Visit avocafe.ca to see the full list of ingredients and allergens before you go."
          }
        ]
      }
    ]
  }
};
