// Auto-generated by scripts/generate-bundled-audio.mjs — do not edit by hand.
export type AudioSentence = { start: number; duration: number; text: string };
export type AudioSegment = { speaker: string; start: number; duration: number; sentences: AudioSentence[] };
export type AudioEntry = { group: string; src: string; bitrate: number; durationSec: number; segments: AudioSegment[] };

export const audioManifest: Record<string, AudioEntry> = {
  "L1": {
    "group": "mock01",
    "src": "/audio/mock01/L1.mp3?v=e87bf1f5",
    "bitrate": 32,
    "durationSec": 50.48,
    "segments": [
      {
        "speaker": "AGENT",
        "start": 0,
        "duration": 4.68,
        "sentences": [
          {
            "start": 0,
            "duration": 4.37,
            "text": "Halton Home Services, this is Priya. How may I help you?"
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 4.68,
        "duration": 4.61,
        "sentences": [
          {
            "start": 0,
            "duration": 4.3,
            "text": "Hi — I've got water coming through the ceiling of my kitchen from the bathroom upstairs."
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 9.29,
        "duration": 3.72,
        "sentences": [
          {
            "start": 0,
            "duration": 3.41,
            "text": "I'm sorry to hear that. Have you turned off the water at the main valve?"
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 13.02,
        "duration": 2.33,
        "sentences": [
          {
            "start": 0,
            "duration": 2.02,
            "text": "Not yet — I wasn't sure where it is."
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 15.35,
        "duration": 5.09,
        "sentences": [
          {
            "start": 0,
            "duration": 4.78,
            "text": "It's usually in the basement near the front wall. I'd turn it off right away to stop further damage."
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 20.44,
        "duration": 4.61,
        "sentences": [
          {
            "start": 0,
            "duration": 4.3,
            "text": "Okay, I'll do that now. How soon can someone come?"
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 25.05,
        "duration": 4.92,
        "sentences": [
          {
            "start": 0,
            "duration": 4.61,
            "text": "We have a plumber finishing a job in your area. He can be there within the hour."
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 29.97,
        "duration": 3,
        "sentences": [
          {
            "start": 0,
            "duration": 2.69,
            "text": "That's fine. What's the cost?"
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 32.98,
        "duration": 15.6,
        "sentences": [
          {
            "start": 0,
            "duration": 15.29,
            "text": "There's a standard call-out fee of eighty dollars, covering the first thirty minutes. After that it's billed per fifteen-minute block at twenty-five dollars. Parts are extra, but we'll confirm any cost before starting repairs."
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 48.58,
        "duration": 1.9,
        "sentences": [
          {
            "start": 0,
            "duration": 1.9,
            "text": "Great — please send someone over."
          }
        ]
      }
    ]
  },
  "L2": {
    "group": "mock01",
    "src": "/audio/mock01/L2.mp3?v=bc74bd2e",
    "bitrate": 32,
    "durationSec": 41.97,
    "segments": [
      {
        "speaker": "LEE",
        "start": 0,
        "duration": 2.57,
        "sentences": [
          {
            "start": 0,
            "duration": 2.26,
            "text": "You look tired. Long week?"
          }
        ]
      },
      {
        "speaker": "MARA",
        "start": 2.57,
        "duration": 4.85,
        "sentences": [
          {
            "start": 0,
            "duration": 4.54,
            "text": "Tell me about it. I've been working late every night because of a project deadline."
          }
        ]
      },
      {
        "speaker": "LEE",
        "start": 7.42,
        "duration": 3.24,
        "sentences": [
          {
            "start": 0,
            "duration": 2.93,
            "text": "Well, the good news is the weather's supposed to be beautiful this weekend."
          }
        ]
      },
      {
        "speaker": "MARA",
        "start": 10.67,
        "duration": 4.49,
        "sentences": [
          {
            "start": 0,
            "duration": 4.18,
            "text": "Really? I was thinking of finally checking out that new trail by the river."
          }
        ]
      },
      {
        "speaker": "LEE",
        "start": 15.16,
        "duration": 7.56,
        "sentences": [
          {
            "start": 0,
            "duration": 7.25,
            "text": "I did it last Saturday — it's about six kilometres, mostly flat, and there's a little cafe at the halfway point."
          }
        ]
      },
      {
        "speaker": "MARA",
        "start": 22.72,
        "duration": 3.89,
        "sentences": [
          {
            "start": 0,
            "duration": 3.58,
            "text": "That sounds perfect. Are you free on Sunday morning?"
          }
        ]
      },
      {
        "speaker": "LEE",
        "start": 26.61,
        "duration": 4.2,
        "sentences": [
          {
            "start": 0,
            "duration": 3.89,
            "text": "I have a dentist appointment at nine, but I could meet you around eleven."
          }
        ]
      },
      {
        "speaker": "MARA",
        "start": 30.81,
        "duration": 5.01,
        "sentences": [
          {
            "start": 0,
            "duration": 4.7,
            "text": "Eleven works. Should we drive separately or meet at the trailhead?"
          }
        ]
      },
      {
        "speaker": "LEE",
        "start": 35.83,
        "duration": 4.05,
        "sentences": [
          {
            "start": 0,
            "duration": 3.74,
            "text": "The parking lot fills up early, so I'll pick you up at ten forty-five."
          }
        ]
      },
      {
        "speaker": "MARA",
        "start": 39.88,
        "duration": 2.09,
        "sentences": [
          {
            "start": 0,
            "duration": 2.09,
            "text": "Great — I'll bring water and a hat."
          }
        ]
      }
    ]
  },
  "L3": {
    "group": "mock01",
    "src": "/audio/mock01/L3.mp3?v=f0eab2fd",
    "bitrate": 32,
    "durationSec": 47.89,
    "segments": [
      {
        "speaker": "ANNOUNCER",
        "start": 0,
        "duration": 47.89,
        "sentences": [
          {
            "start": 0,
            "duration": 15.17,
            "text": "Welcome to the Riverside Public Library's fall program launch. Starting October first, we're introducing three new services. First, an extended Saturday storytime for children aged three to six, running from ten to eleven in the community room."
          },
          {
            "start": 15.29,
            "duration": 21.46,
            "text": "Second, a free digital-skills help desk every Tuesday and Thursday afternoon, where volunteers can assist with phones, tablets and laptops — no appointment needed. Third, a home-delivery service for cardholders who cannot visit the library in person; deliveries go out every second Wednesday and can be arranged by phone or through our website."
          },
          {
            "start": 36.87,
            "duration": 11.02,
            "text": "All three services are free, but storytime and home delivery require registration in advance. Registration opens this Friday at nine a.m. at the front desk and online."
          }
        ]
      }
    ]
  },
  "L4": {
    "group": "mock01",
    "src": "/audio/mock01/L4.mp3?v=994b6bf4",
    "bitrate": 32,
    "durationSec": 44.62,
    "segments": [
      {
        "speaker": "NEWS READER",
        "start": 0,
        "duration": 44.62,
        "sentences": [
          {
            "start": 0,
            "duration": 21.34,
            "text": "The city council voted last night to approve funding for a new pedestrian bridge across the Don Valley. The bridge, which will connect the Eastside neighbourhood with the downtown core, is expected to cost eighteen million dollars and take two years to complete. Construction is scheduled to begin next spring, following a final public consultation in December."
          },
          {
            "start": 21.46,
            "duration": 13.82,
            "text": "Supporters say the bridge will cut the current forty-minute walking detour down to just ten minutes and encourage cycling. Opponents argue the money would be better spent repairing existing roads, several of which have been closed since last winter's flooding."
          },
          {
            "start": 35.4,
            "duration": 9.22,
            "text": "The mayor called the decision 'a long-term investment in a greener, more connected city', while acknowledging that some road repairs will be delayed as a result."
          }
        ]
      }
    ]
  },
  "L5": {
    "group": "mock01",
    "src": "/audio/mock01/L5.mp3?v=634ed90f",
    "bitrate": 32,
    "durationSec": 63.93,
    "segments": [
      {
        "speaker": "HOST",
        "start": 0,
        "duration": 13.25,
        "sentences": [
          {
            "start": 0,
            "duration": 12.94,
            "text": "Welcome back. Today we're asking: has the shift to remote work been good for our cities? With me are economist Dr. Elena Roth and small-business owner Marcus Webb. Elena, let's start with you."
          }
        ]
      },
      {
        "speaker": "ELENA",
        "start": 13.25,
        "duration": 12.17,
        "sentences": [
          {
            "start": 0,
            "duration": 11.86,
            "text": "Thanks. The data shows a clear split. Knowledge workers report higher satisfaction and save commuting costs, but downtown businesses have lost foot traffic — lunch spots and transit have felt it most."
          }
        ]
      },
      {
        "speaker": "HOST",
        "start": 25.42,
        "duration": 2.85,
        "sentences": [
          {
            "start": 0,
            "duration": 2.54,
            "text": "Marcus, you run a print shop downtown."
          }
        ]
      },
      {
        "speaker": "MARCUS",
        "start": 28.28,
        "duration": 8.49,
        "sentences": [
          {
            "start": 0,
            "duration": 8.18,
            "text": "That's right. Our daytime customers dropped by almost half. But we've adapted — we now offer delivery and early-evening hours, and we've kept everyone employed."
          }
        ]
      },
      {
        "speaker": "HOST",
        "start": 36.77,
        "duration": 2.49,
        "sentences": [
          {
            "start": 0,
            "duration": 2.18,
            "text": "Elena, what about the long term?"
          }
        ]
      },
      {
        "speaker": "ELENA",
        "start": 39.26,
        "duration": 13.41,
        "sentences": [
          {
            "start": 0,
            "duration": 13.1,
            "text": "Offices aren't disappearing; they're changing. We're likely to settle on three days in, two days out. That hybrid model spreads demand more evenly and is better for the city's finances than full remote."
          }
        ]
      },
      {
        "speaker": "MARCUS",
        "start": 52.67,
        "duration": 8.69,
        "sentences": [
          {
            "start": 0,
            "duration": 8.38,
            "text": "I'd agree with that. A steady three-day week would bring enough people back to keep the lunch economy alive, without losing the flexibility workers now expect."
          }
        ]
      },
      {
        "speaker": "HOST",
        "start": 61.36,
        "duration": 2.57,
        "sentences": [
          {
            "start": 0,
            "duration": 2.57,
            "text": "So a middle path, then. Thanks to you both."
          }
        ]
      }
    ]
  },
  "L6": {
    "group": "mock01",
    "src": "/audio/mock01/L6.mp3?v=a95a3812",
    "bitrate": 32,
    "durationSec": 46.2,
    "segments": [
      {
        "speaker": "SPEAKER A",
        "start": 0,
        "duration": 22.63,
        "sentences": [
          {
            "start": 0,
            "duration": 15.14,
            "text": "E-bikes have no place on our park trails. Trails are for walking and traditional cycling, and motor-assisted bikes move too fast for a space meant for families and dogs. I've nearly been clipped twice this month. If we allow e-bikes everywhere, we'll push walkers out of the parks entirely."
          },
          {
            "start": 15.26,
            "duration": 7.06,
            "text": "A speed limit is unenforceable on a narrow path, so the only fair rule is to keep motor power off the trails."
          }
        ]
      },
      {
        "speaker": "SPEAKER B",
        "start": 22.63,
        "duration": 23.57,
        "sentences": [
          {
            "start": 0,
            "duration": 23.57,
            "text": "I understand the worry, but a blanket ban ignores who actually rides e-bikes — commuters and older riders who otherwise wouldn't cycle at all. The real issue isn't the motor; it's courtesy. A fifteen-kilometre speed limit, clearly posted, plus fines for reckless riding, would let everyone share the trail safely. We shouldn't punish a whole group for the behaviour of a few."
          }
        ]
      }
    ]
  },
  "lst-01": {
    "group": "practice",
    "src": "/audio/practice/lst-01.mp3?v=22d7816f",
    "bitrate": 32,
    "durationSec": 36.2,
    "segments": [
      {
        "speaker": "AGENT",
        "start": 0,
        "duration": 4.25,
        "sentences": [
          {
            "start": 0,
            "duration": 3.94,
            "text": "TechFix support, Maya speaking. How can I help you?"
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 4.25,
        "duration": 6.65,
        "sentences": [
          {
            "start": 0,
            "duration": 6.34,
            "text": "Hi — I bought a laptop charger from your website last week and it arrived already cracked. The cable's frayed near the tip."
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 10.9,
        "duration": 4.13,
        "sentences": [
          {
            "start": 0,
            "duration": 3.82,
            "text": "I'm sorry about that. Could you share your order number so I can look it up?"
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 15.04,
        "duration": 3.53,
        "sentences": [
          {
            "start": 0,
            "duration": 3.22,
            "text": "Sure, it's 8-3-2-1-7-0-4."
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 18.57,
        "duration": 8.37,
        "sentences": [
          {
            "start": 0,
            "duration": 8.06,
            "text": "Thanks. I can see the order was placed six days ago. We'll send a replacement free of charge, and you don't need to return the damaged one."
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 26.94,
        "duration": 2.97,
        "sentences": [
          {
            "start": 0,
            "duration": 2.66,
            "text": "That's great. How long will it take?"
          }
        ]
      },
      {
        "speaker": "AGENT",
        "start": 29.91,
        "duration": 5.04,
        "sentences": [
          {
            "start": 0,
            "duration": 4.73,
            "text": "Around three to five business days. You'll receive a tracking email shortly."
          }
        ]
      },
      {
        "speaker": "CUSTOMER",
        "start": 34.95,
        "duration": 1.25,
        "sentences": [
          {
            "start": 0,
            "duration": 1.25,
            "text": "Perfect, that solves it."
          }
        ]
      }
    ]
  },
  "lst-02": {
    "group": "practice",
    "src": "/audio/practice/lst-02.mp3?v=e23288aa",
    "bitrate": 32,
    "durationSec": 30.58,
    "segments": [
      {
        "speaker": "ANNOUNCER",
        "start": 0,
        "duration": 30.58,
        "sentences": [
          {
            "start": 0,
            "duration": 24.41,
            "text": "Avo Cafe on Maple Street has just launched its autumn menu. From today until the end of November, every weekday between three and five, you can grab a seasonal drink and any sandwich for nine dollars. The new menu features a pumpkin latte, pear and gorgonzola toastie, and a maple butter brioche. Students who show a valid ID also receive a ten percent discount on bakery items."
          },
          {
            "start": 24.53,
            "duration": 6.05,
            "text": "Visit avocafe.ca to see the full list of ingredients and allergens before you go."
          }
        ]
      }
    ]
  }
};
